version: "3"
services:
  hub:
    image: selenium/hub:4.7.2-20221219
    container_name: selenium-hub-epam-1
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:4.7.2-20221219
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=4
  firefox:
    image: selenium/node-firefox:4.7.2-20221219
    shm_size: 1gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=4
      - SE_NODE_MAX_SESSIONS=4
  chrome2:
    image: selenium/node-chrome:4.8.0-20230202
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_INSTANCES=2
      - SE_NODE_MAX_SESSIONS=2
  chrome_video:
    image: selenium/video:ffmpeg-4.3.1-20221219
    volumes:
      - E:\MAX\IT\Logging\java_for_testers\chrome:/videos
    depends_on:
      - chrome
    environment:
      - DISPLAY_CONTAINER_NAME=chrome
      - FILE_NAME=chrome_video.mp4
  chrome_video2:
    image: selenium/video:ffmpeg-4.3.1-20230202
    volumes:
      - E:\MAX\IT\Logging\java_for_testers\chrome2:/videos
    depends_on:
      - chrome2
    environment:
      - DISPLAY_CONTAINER_NAME=chrome2
      - FILE_NAME=chrome2_video.mp4
  firefox_video:
    image: selenium/video:ffmpeg-4.3.1-20221219
    volumes:
      - E:\MAX\IT\Logging\java_for_testers\firefox:/videos
    depends_on:
      - firefox
    environment:
      - DISPLAY_CONTAINER_NAME=firefox
      - FILE_NAME=firefox_video.mp4

# docker compose up
# docker compose up  -d --scale chrome=2 --scale edge=2


